version: "3.3"

services:
  api_rest:
    build: .
    image: api_rest:1.0
    networks:
      - api-network
    container_name: api_rest_container
    depends_on:
      - database
    ports:
      - 1323:1323

  database:
    image: postgres:16.2
    networks:
      - api-network
    container_name: database_api
    hostname: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=753159"
      - "POSTGRES_DB=apiDB"
    ports:
      - 2345:5432
    volumes:
      - ./db-init/:/docker-entrypoint-initdb.d/

networks:
  api-network:
    driver: bridge